version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: cache
    ports:
    - 6379:6379
    expose:
      - 6379
  app:
    image: node:14.15.1-alpine3.10
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    links:
      - redis:redis
    ports:
      - 3000:3000
    command: sh -c 'npm i && npm i -g grunt && grunt automatic'
    expose: 
      - 3000
